### PR TITLE
Distribution deserialization

### PR DESCRIPTION
**Pull request by ira-halenok**
Feature: from now on, `Prosimos` should support different input format (more understandable for end-user and not tied to Scipy implementation). For this, some changes in serialisation and deserialisation were required. 

Changes:
- introduced deserialisation used in `Prosimos`
- adjusted serialisation `to_prosimos_distribution` to support a new format
  - I also want to test `Simod` somehow in order to verify that it will work correctly with new implementations of both `Prosimos` and `pix-framework`. I would appreciate it if you could provide any guidance on how I should proceed with testing that.
- introduced `generate_one_value_with_boundaries`. `min` and `max` properties are used to limit the range of possible generated values. So instead of doing it solely in Prosimos, I added this functionality here so that others can use it if needed.
- covered changed logic with unit tests.

### CODE REVIEW

**Review by iharsuvorau — APPROVED** [review]
Looks good. Thank you. 

We didn't mention before, when we started working on code bases together with David, we decided on a common code formatting tool, Black https://black.readthedocs.io/en/stable/. Before, we'd been using PyCharm's default formatter which doesn't work in VS Code or other editors, for example. Black kind of solves the issue of unifying the look of the code. 

I'll reformat your changes myself after merging, because I also want to adjust the CI pipeline not to assign a tag on PR. But, if you have any issues with Black or other proposals, let's discuss.

**Review by iharsuvorau — APPROVED** [review]

**Comment by iharsuvorau** [comment]
>   * I also want to test `Simod` somehow in order to verify that it will work correctly with new implementations of both `Prosimos` and `pix-framework`. I would appreciate it if you could provide any guidance on how I should proceed with testing that.

In short, I'll run tests for Simod myself :)

To test Simod with new changes, we need to download Simod's source, update the version of `pix-framework` to the newest one, install everything and run Simod tests (that can take 20+ min on a laptop, and 80+ min in GitHub Actions' machines).

It would be good to have a script or a separate CI manifest for this where we can test not only Simod, but all other dependent packages if they aren't broken by changes to `pix-framework`. GitHub actually shows the dependencies on the main page of the repo, here's the detailed view https://github.com/AutomatedProcessImprovement/pix-framework/network/dependents. But, this requires some time. If you have some, you can take it. Otherwise, we just rely on manual debugging: when a package author updates dependencies' versions and runs tests, this is when we find out if something is broken.

**Comment by ira-halenok** [comment]
> Looks good. Thank you.
> 
> We didn't mention before, when we started working on code bases together with David, we decided on a common code formatting tool, Black https://black.readthedocs.io/en/stable/. Before, we'd been using PyCharm's default formatter which doesn't work in VS Code or other editors, for example. Black kind of solves the issue of unifying the look of the code.
> 
> I'll reformat your changes myself after merging, because I also want to adjust the CI pipeline not to assign a tag on PR. But, if you have any issues with Black or other proposals, let's discuss.

I have no objections for `Black`, so everything sounds good to me. Thanks for formatting changes.

**Comment by ira-halenok** [comment]
>>
> 
> In short, I'll run tests for Simod myself :)

Thank you. And let me know in case something doesn't work.

**Pull request merged**
